# - name: Add APT key
#   apt_key:
#     url: https://mirror.yandex.ru/mirrors/repo.mongodb.org/apt/ubuntu/dists/xenial/mongodb-org/3.2/Release.gpg
#   tags: install

- name: Add APT repository
  apt_repository:
    repo: deb [ arch=amd64,arm64 ] https://mirror.yandex.ru/mirrors/repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
    state: present
  tags: install

- name: Install mongodb package
  apt:
    name: mongodb-org
    state: present
  tags: install

- name: Configure service supervisor
  systemd:
    name: mongodb
    enabled: yes
    state: started
  tags: install
